"""add_is_primary_to_contact

Revision ID: ae87ba6da6a6
Revises: 2d2c5447ee0f
Create Date: 2026-05-25 20:34:34.982472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae87ba6da6a6'
down_revision: Union[str, Sequence[str], None] = '2d2c5447ee0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_primary', sa.Boolean(), nullable=True))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('contact_name')
        batch_op.drop_column('contact_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_id', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('contact_name', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('is_primary')

    # ### end Alembic commands ###
