"""add_contract_payment_type_direct_costs

Revision ID: f2892c9d57a1
Revises: ae87ba6da6a6
Create Date: 2026-05-27 10:04:52.169567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2892c9d57a1'
down_revision: Union[str, Sequence[str], None] = 'ae87ba6da6a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direct_costs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('contract_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('cost_date', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('direct_costs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_direct_costs_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_direct_costs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_direct_costs_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_type', sa.String(), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('payment_type')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_column('contract_type')

    with op.batch_alter_table('direct_costs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_direct_costs_project_id'))
        batch_op.drop_index(batch_op.f('ix_direct_costs_id'))
        batch_op.drop_index(batch_op.f('ix_direct_costs_contract_id'))

    op.drop_table('direct_costs')
    # ### end Alembic commands ###
